### ISSUE TITLE
undeclared identifier: 'getMyOSConfig'

### ISSUE THREAD

**Issue by TensorTom** [iffy/wiish#62]
I followed the install/init instructions:

```
wiish init wisher
cd wisher
wiish run
```

Here is what I get:

```
/home/tensortom/.nimble/pkgs/wiish-0.1.0/wiishpkg/baseapp.nim(19, 16) Error: undeclared identifier: 'getMyOSConfig'
/tmp/nimble_12224/githubcom_iffywiishgit/wiishpkg/building/buildutil.nim(31) run
Error: unhandled exception: Error running process [CatchableError]

```

**Comment by TensorTom** [comment]
I also tried `wiish build --target linux` and got the message about Linux not being supported. Have you considered using one of these?:

https://github.com/oskca/webview

https://github.com/dom96/webdriver/blob/master/src/webdriver.nim

**Comment by TensorTom** [comment]
I have started a project similar to yours but a bit different. Please see my webview in `main.nim` and `index.html`: https://github.com/TensorTom/Trifecta/tree/master/build-template/nim

**Comment by iffy** [comment]
Thanks for this report.  I'll admit that my focus has been more on mobile apps than desktop at this point.  Webview is one of the supported desktop/mobile GUI platforms (though I haven't gotten to Linux, obviously).  I'll fix this bug when I get a chance.

I am designing wiish so that it could use whatever GUI library you wanted (including the ones you linked and the one you're making).  Wiish will provide auto-updating, logging, packaging, installer-making, etc...
